### ISSUE TITLE
Listado de referencias QGIS personales

### ISSUE THREAD

**Issue by msevilla00** [sigdeletras/qgis_recursos#2]
Por si te interesa añadirlo, aquí te pego algunas referencias bibliográficas que tengo de QGIS que les paso a los alumnos aunque hay que actualizarlo, puede servirte de base (o ya te lo paso actualizado en otro momento):

---
title: "Enlaces y referencias de QGIS"
author: "Miguel Sevilla-Callejo"
filename: "QGIS_referencias.md"

---

# Referencias y enlaces sobre QGIS

* [Bibliografía](#bibliografía)
	* [Teoría SIG](#teoría-sig)
	* [Manuales QGIS y GRASS](#manuales-qgis-y-grass)
	* [Referencias antiguas](#referencias-antiguas)
* [Enlaces](#enlaces)
	* [Otros enlaces](#otros-enlaces)

## Bibliografía

* Últimos [manuales de QGIS en PDF](http://docs.qgis.org/testing/pdf/)

### Teoría SIG
**Olaya,Victor (2011).** *Sistemas de Información
Geográfica*,OSGeo, Libro electrónico, Versión 1.0 Disponible en: [http://wiki.osgeo.org/wiki/Libro\_SIG](http://wiki.osgeo.org/wiki/Libro_SIG)

### Manuales QGIS y GRASS

AÑADIR Mastering QGIS: [enlace](https://www.packtpub.com/big-data-and-business-intelligence/mastering-qgis-second-edition)

**Graser, Anita (2014).** *Learning QGIS - Second Edition*. Packt Publishing.
Segunda edición ampliada y actualizada del libro *Learning QGIS 2.0*. Más información en la [web de la editorial](https://www.packtpub.com/application-development/learning-qgis-second-edition). -- VAN POR LA TERCERA edición

**QGIS Development Team (2015).** *QGIS User Guide. Release 2.6*, OSGeo.
Disponible en [HTML](http://docs.qgis.org/2.6/en/docs/user_manual/) o en [PDF](http://docs.qgis.org/2.6/pdf/en/QGIS-2.6-UserGuide-en.pdf) en la web de documentación del proyecto

**Neteler, M. & Mitasova, H., 2008.** *Open Source GIS: A GRASS GIS Approach*, Springer
Acceso al texto completo [a través de la red del CSIC](http://aleph.csic.es/F?func=find-c&ccl_term=SYS%3D001209034&local_base=ELECTRONICOS) y más información en la [web del libro](http://grassbook.org/)

**Sherman, Gary E. (2012).** *The Geospatial Desktop. Open Source GIS & Mapping*, Locate Press.
Más información en la [web de la editorial](http://locatepress.com/gsd) o la [web del libro](http://geospatialdesktop.com/))

**Sherman, Gary (2014).** *The Pyqgis Programmer’s Guide*. Chugiak, Alaska: Locate Press. Más información en la [web de la editorial](https://locatepress.com/ppg) o del [libro](http://pyqgis.org/). Basado en el *PyQGIS Developer Cookbook* accesible a través de la [web de QGIS](http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/) y disponible para [descarga en PDF (v.2.2)](http://docs.qgis.org/2.2/pdf/en/QGIS-2.2-PyQGISDeveloperCookbook-en.pdf)

**Thiede, Rudiger, Tim Sutton, and Horst Duster (2013).** *The Quantum GIS Training Manual*. Locate Press. Más información en la [web de la editorial](https://locatepress.com/qtm), acceso abierto en [web del libro](http://docs.qgis.org/2.6/en/docs/training_manual/) y posibilidad de descarga de ebook en [PDF](http://docs.qgis.org/2.6/pdf/en/QGIS-2.6-QGISTrainingManual-en.pdf)

### Referencias antiguas

**Dasseau, O.(Coord.), 2013.** *Quantum GIS 1.8- User Manual*, OSGeo.
Disponible en [la web de documentación del proyecto](http://qgis.org/en/documentation/manuals.html)

**Graser, Anita (2013).** *Learning QGIS 2.0*. Packt Publishing.
Más información en la [web de la editorial](http://www.packtpub.com/learning-qgis-2-0-to-create-maps-and-perform-geoprocessing-tasks/book).

**Sherman, Gary E. (2008).** *Desktop GIS: Mapping the Planet with Open Source Tools*. Pragmatic Bookshelf. - Libro descatalogado, reescrito y reeditado en 2012: *The Geospatial Desktop. Open Source GIS & Mapping*.

## Enlaces

La práctica totalidad de la documentación relativa al uso de Quantum GIS y GRASS puede consultarse en las respectivas páginas web de cada uno de los proyectos. Aunque mayoritariamente la documentación se encuentra en inglés existen algunos manuales y secciones de la ayuda también en castellano.

* [QGIS Documentation](http://www.qgis.org/en/docs/index.html)

* [GRASS Documentation](http://grass.osgeo.org/documentation/)

* [Planet QGIS](http://qgis.org/planet/) - resumen de principales blogs sobre QGIS

* [QGIS - StackExchange](http://gis.stackexchange.com/questions/tagged/qgis)

* [QGIS Tutorials and Tips](http://www.qgistutorials.com/en/)

**Comment by sigdeletras** [comment]
Agregado. Casi lo veo como un apartado dentro del repositorio pero por ahora lo añado aquí. Mil gracias @msevilla00
